# Harbor Helm Chart Values
# This configuration sets up Harbor with HTTPS and proper certificates

expose:
  type: nodePort
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: "harbor-tls"
      notarySecretName: "notary-tls"
  nodePort:
    name: harbor
    ports:
      https:
        port: 443
        nodePort: 30443
      notary:
        port: 4443
        nodePort: 30444

# External URL - change this to your actual domain/IP
externalURL: https://harbor.local:30443

# Harbor admin password
harborAdminPassword: "Harbor12345"

# Database settings
database:
  type: internal

# Redis settings  
redis:
  type: internal

# Storage settings
persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: ""
      size: 5Gi
    chartmuseum:
      storageClass: ""
      size: 5Gi
    jobservice:
      storageClass: ""
      size: 1Gi
    database:
      storageClass: ""
      size: 1Gi
    redis:
      storageClass: ""
      size: 1Gi

# Nginx settings
nginx:
  image:
    repository: goharbor/nginx-photon
    tag: v2.10.0

# Core settings
core:
  image:
    repository: goharbor/harbor-core
    tag: v2.10.0

# Portal settings
portal:
  image:
    repository: goharbor/harbor-portal
    tag: v2.10.0

# Registry settings
registry:
  registry:
    image:
      repository: goharbor/registry-photon
      tag: v2.10.0
  controller:
    image:
      repository: goharbor/harbor-registryctl
      tag: v2.10.0

# Chartmuseum settings
chartmuseum:
  enabled: true
  image:
    repository: goharbor/chartmuseum-photon
    tag: v2.10.0

# Notary settings
notary:
  enabled: true
  server:
    image:
      repository: goharbor/notary-server-photon
      tag: v2.10.0
  signer:
    image:
      repository: goharbor/notary-signer-photon
      tag: v2.10.0

# Trivy scanner
trivy:
  enabled: true
  image:
    repository: goharbor/trivy-adapter-photon
    tag: v2.10.0