apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-port-5000
  namespace: default
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 5000
