# Updated workflow with Docker Hub Token Authentication & Harbor Registry
name: CI/CD Pipeline with Enhanced Security
on: push
env:
  DOCKER_IMAGE: apenzijngek/student535961-app
  HARBOR_REGISTRY: harbor.local:30443
  HARBOR_PROJECT: student535961
jobs:
  build:
    name: Build & Push to Registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      # Docker Hub login with TOKEN (not password!)
      - name: Login to Docker Hub (Token Auth)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}  # Contains ACCESS TOKEN
          
      # Harbor registry login (if available)
      - name: Login to Harbor Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
        continue-on-error: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            
      - name: Build and push to Harbor (optional)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/quoter-app:latest
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/quoter-app:${{ github.sha }}
        continue-on-error: true
        
  scan:
    name: Security Scan
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub (Token Auth)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}  # Contains ACCESS TOKEN
          
      - name: Docker Scout CVE Scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.DOCKER_IMAGE }}:latest
          only-fixed: true
          only-severities: critical,high
          ignore-base: false
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exit-code: never
          
      - name: Generate SBOM
        uses: docker/scout-action@v1
        with:
          command: sbom
          image: ${{ env.DOCKER_IMAGE }}:latest
          output: ./sbom.json
          
  test:
    name: Integration Test
    needs: [ scan ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub (Token Auth)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}  # Contains ACCESS TOKEN

  postman-security-test:
    name: Security Headers Test
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Newman
        run: npm install -g newman
      
      - name: Run Postman Collection
        run: |
          newman run "https://api.postman.com/collections/${{ secrets.POSTMAN_COLLECTION_ID }}?apikey=${{ secrets.POSTMAN_API_KEY }}"
        continue-on-error: true
        
      - name: Upload Newman results
        if: always()
        uses: actions/upload-artifact@v4  # v4 in plaats van v3
        with:
          name: newman-results
          path: newman/
